version: "3.8"
 # update docker-compose to run the image of the db and the image from dockerfile, put them in the same network, set image name

services:
  project-dms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: project-dms
    depends_on:
      - db
  db:
    container_name: drugstore_management_system
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muki93
      PGDATA: /data/postgres
      POSTGRES_DB: drugstore_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5342:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: