version: "3.8"

services:
  db:
    container_name: drugstore_management_system
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muki93
      PGDATA: /data/postgres
      POSTGRES_DB: drugstore_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5342:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: