server:
  port: 8080

  info:
    application:
      name: drugstore-management-system
      description: A management system app for drugstores.
      author: Muharem Spica
      version: '@project.version@'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/drugstore_db
    username: postgres
    password: muki93

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    level:
      org.springframework: info
      org.hibernate: info

